#%RAML 1.0 Extension

extends: profileApi-base.raml

version: v2

uses:
  hypermediaType: library/hypermedia-Types.raml
  commonResourceType: library/common-ResourceTypes.raml
  profileType: profileApi-hypermedia-Types.raml

/profiles:
  type:
    commonResourceType.collection:
      collectionResponseType: profileType.profileCollectionResponse
      errorResponseType: hypermediaType.errorResponse
      collectionMemberPrototypeType: profileType.profilePrototype
      collectionMemberResponseType: profileType.profileResponse
  /{profileId}:
    type:
      commonResourceType.collectionMember:
        errorResponseType: hypermediaType.errorResponse
        collectionMemberPrototypeType: profileType.profilePrototype
        collectionMemberResponseType: profileType.profileResponse
        defaultResponseType: hypermediaType.defaultResponse
    /friends:
      type:
        commonResourceType.collectionMemberRelatedCollection:
          collectionMemberRelatedCollectionResponseType: profileType.friendCollectionResponse
          errorResponseType: hypermediaType.errorResponse
          collectionMemberRelatedCollectionMemberPrototypeType: profileType.friendPrototype
          collectionMemberRelatedCollectionMemberResponseType: profileType.friendCollectionMemberResponse
      get:
        is: &collectionTraits [ commonTrait.pageable, commonTrait.sortable ]
        securedBy: &registeredUsers
          security.oauth2:
            scopes: [ registered ]
      post:
        securedBy: *registeredUsers
        
      /{friendId}:
        uriParameters:
          friendId: profileType.friendId
        type:
          commonResourceType.collectionMemberRelatedCollectionMember:
            errorResponseType: hypermediaType.errorResponse
            defaultResponseType: hypermediaType.defaultResponse
        delete:
          securedBy: *registeredUsers
